-- Ryan Schulz
-- Assignment2
-- COEN 280 Spring 2019

DROP TABLE RATING;
DROP TABLE GENRE;
DROP TABLE DIRECTOR;
DROP TABLE ACTOR;
DROP TABLE ROLES;
DROP TABLE MOVIE;
DROP TABLE PERSON;
DROP TABLE IMDB_USER;