-- Ryan Schulz
-- Assignment2
-- COEN 280 Spring 2019
SELECT DISTINCT P.NAME AS DIRECTOR_NAME, M.NAME AS MOVIES_DIRECTED, M.YEAR AS MOVIE_YEAR
FROM PERSON P, DIRECTOR D, MOVIE M,  GENRE G
WHERE M.MID=G.MID AND M.MID=D.MID AND G.GENRE_TYPE='Drama' AND D.PID=P.PID AND MOD(M.YEAR,4)=0;
