-- Ryan Schulz
-- Assignment2
-- COEN 280 Spring 2019
SELECT P.NAME AS ACTOR_NAME
FROM PERSON P,MOVIE M,ACTOR A
WHERE A.PID=P.PID AND M.MID=A.MID
GROUP BY P.NAME
HAVING COUNT(DISTINCT M.DIRECTOR_ID)>3;