-- Ryan Schulz
-- Assignment2
-- COEN 280 Spring 2019
SELECT DISTINCT M.NAME AS MOVIE_NAME, (MAX(R.RATING) - MIN(R.RATING)) AS RATING_SPAN
FROM RATING R, MOVIE M
WHERE M.MID = R.MID
GROUP BY R.MID, M.NAME
ORDER BY RATING_SPAN DESC;