-- Ryan Schulz
-- Assignment2
-- COEN 280 Spring 2019
SELECT DISTINCT A.PID AS ACTOR_NOT_UNEMPLOYED
FROM ACTOR A, MOVIE M, MOVIE M1
WHERE A.MID = M.MID 
	AND A.MID = M1.MID
	AND NOT M1.MID = M.MID
	AND M.YEAR-M1.YEAR <= 2;