-- Ryan Schulz
-- Assignment2
-- COEN 280 Spring 2019
SELECT (AVG(BEFORE_2005.AVERAGE_RATING) - AVG(AFTER_2005.AVERAGE_RATING)) AS AVERAGE_RATING
FROM (
	SELECT AVG(R.RATING) AS AVERAGE_RATING
	FROM MOVIE M, RATING R
	WHERE M.YEAR >2005 AND R.MID = M.MID
	GROUP BY R.MID
	) AFTER_2005,
	(
	SELECT AVG(R.RATING) AS AVERAGE_RATING
	FROM MOVIE M, RATING R
	WHERE M.YEAR <2005 AND R.MID = M.MID
	GROUP BY R.MID
	) BEFORE_2005;